export const collectionPillars = [
  {
    eyebrow: "Sculptural calm",
    title: "A shape that settles the room",
    text: "Every piece is designed to bring balance, allowing light, proportion, and texture to feel intentional rather than loud.",
  },
  {
    eyebrow: "Refined materials",
    title: "Hand-finished details",
    text: "From brushed metal edges to softly polished glass, the collection keeps a tactile richness that rewards a closer look.",
  },
  {
    eyebrow: "Timeless presence",
    title: "Built to stay relevant",
    text: "The silhouettes lean classic, but never rigid, so they move naturally across interiors, seasons, and styles.",
  },
];

export const mirrorCollections = [
  {
    id: 1,
    slug: "aurelia-arc",
    name: "Aurelia Arc",
    tag: "Best seller",
    bestSeller: true,
    price: 1290,
    shape: "Arch",
    finish: "Brass",
    room: "Entryway",
    size: "Large",
    image: "/aurelia-arc.png",
    description:
      "A graceful arched silhouette with warm brass notes and a gallery-like finish.",
  },
  {
    id: 2,
    slug: "celeste-round",
    name: "Celeste Round",
    tag: "Best seller",
    bestSeller: true,
    price: 1080,
    shape: "Round",
    finish: "Bronze",
    room: "Bedroom",
    size: "Medium",
    image: "/celeste-round.jpg",
    description:
      "A softened profile that brings quiet symmetry to bedrooms, salons, and reading corners.",
  },
  {
    id: 3,
    slug: "orion-slim",
    name: "Orion Slim",
    tag: "Modern classic",
    bestSeller: true,
    price: 890,
    shape: "Linear",
    finish: "Steel",
    room: "Dressing Room",
    size: "Tall",
    image: "/orion-slim.jpg",
    description:
      "Minimal in form, crisp in presence, and designed for spaces that want a lighter touch.",
  },
  {
    id: 4,
    slug: "solene-halo",
    name: "Solene Halo",
    tag: "New arrival",
    bestSeller: false,
    price: 1150,
    shape: "Round",
    finish: "Brass",
    room: "Living Room",
    size: "Medium",
    image: "/lumiere-arch.webp",
    description:
      "A glowing circular frame that reads soft and luminous without losing definition.",
  },
  {
    id: 5,
    slug: "marlow-arch",
    name: "Marlow Arch",
    tag: "Gallery piece",
    bestSeller: false,
    price: 1210,
    shape: "Arch",
    finish: "Oak",
    room: "Dining Room",
    size: "Large",
    image: "/mirror.png",
    description:
      "A tall architectural frame with a warmer finish for rooms that lean collected and calm.",
  },
  {
    id: 6,
    slug: "eira-oval",
    name: "Eira Oval",
    tag: "Soft edge",
    bestSeller: false,
    price: 960,
    shape: "Oval",
    finish: "Bronze",
    room: "Bathroom",
    size: "Medium",
    image: "/lumiere-arch.jpg",
    description:
      "A refined oval silhouette that softens stone, tile, and cabinetry with ease.",
  },
  {
    id: 7,
    slug: "noa-prism",
    name: "Noa Prism",
    tag: "Statement",
    bestSeller: false,
    price: 1020,
    shape: "Linear",
    finish: "Steel",
    room: "Hallway",
    size: "Tall",
    image: "/hero-bg.png",
    description:
      "Sharp, minimal, and quietly dramatic for interiors that want clean geometry.",
  },
  {
    id: 8,
    slug: "vela-vertical",
    name: "Vela Vertical",
    tag: "Tailored",
    bestSeller: false,
    price: 1030,
    shape: "Linear",
    finish: "Brass",
    room: "Bedroom",
    size: "Tall",
    image: "/aurelia-arc.png",
    description:
      "Designed to add vertical rhythm and a subtle hint of luxury to compact walls.",
  },
  {
    id: 9,
    slug: "elara-curve",
    name: "Elara Curve",
    tag: "Editor’s pick",
    bestSeller: false,
    price: 980,
    shape: "Oval",
    finish: "Bronze",
    room: "Living Room",
    size: "Medium",
    image: "/celeste-round.jpg",
    description:
      "A gentle curve with an editorial feel, ideal for layered and textured rooms.",
  },
];

export const filterGroups = {
  shape: ["All", "Arch", "Round", "Oval", "Linear"],
  finish: ["All", "Brass", "Bronze", "Oak", "Steel"],
  room: ["All", "Entryway", "Living Room", "Bedroom", "Bathroom", "Dining Room", "Hallway", "Dressing Room"],
};

export const collectionActions = [
  "Browse the full collection",
  "Request a styling recommendation",
  "Explore bespoke commissions",
];
