var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/collections/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1-j4lfr._.js")
R.c("server/chunks/ssr/node_modules_09r9c10._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0ujij2t.js")
R.c("server/chunks/ssr/[root-of-the-server]__0bunn2z._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/app_layout_07uf2ib.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_collections_page_actions_0qsd8yq.js")
R.m(45944)
module.exports=R.m(45944).exports
